name: CI PR Develop

on:
  pull_request:
    branches:
      - develop

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar build
        run: npm run build

      - name: Ejecutar test
        run: npm test -- --watch=false
